version: 2.1

jobs:
  build:
    resource_class: small
    docker:
      - image: ubuntu:22.04
    environment:
      SFML_VERSION: "2.5.1"
      CMAKE_VERSION: "3.22.1"
      GPP_VERSION: "11.3.0"
      CLANG_VERSION: "14.0.0"
    steps:
      - checkout
      - run: apt update
      - run: apt-get install -y libsfml-dev
      - run: DEBIAN_FRONTEND=noninteractive TZ=Europe/Brussels apt install -y gcc g++ cmake git
      - run: mkdir -p build
      - run: cd build && cmake ..
      - run: cd build && make
